### ISSUE TITLE
local automatic1111: support for checkpoint picker, inpaint support maybe?

### ISSUE THREAD

**Issue by Charmandrigo** [benrugg/AI-Render#119] opened 2023-07-06 00:25 UTC
### Describe the feature you'd like to see:

Thanks for the hard work on this!, I'd like to make a suggestion since I have my own install on a custom server.
Can you add a checkpoint dropdown picker for the prompt section? I would like to grab one of my existing safetensors I have on my install.
I am assuming it's by default loading the checkpoint that's currently on my webui (or not?), and it's where I currently have to go to switch the current checkpoint.
It would be nice if the addon also let us use inpaint to render around specific areas of the final image, could be maybe masking a chroma keyed flat color background.

### Additional information

For use on a local automatic1111 install

**Comment by benrugg** [comment] 2023-07-06 15:44
Yes, I do plan to do this! I'm going to close this as a duplicate of #25, but I will try to get to it soon

**Closed by benrugg** 2023-07-06 15:44 UTC
