### ISSUE TITLE
Render Routed via API to Automatic1111 Extension Instead

### ISSUE THREAD

**Issue by kenster4000** [benrugg/AI-Render#50] opened 2022-11-30 22:53 UTC
### Describe the feature you'd like to see:

Would love to have the render sent immediately to a Blender tab/extension in A1111... so I can use the models and settings there. Definitely something I could do manually doing it in img2img... but would be awesome to leverage API.

**Comment by benrugg** [comment] 2022-11-30 23:34
Yeah, this is a good idea @kenster4000. I think it's a duplicate of #18, so I'm going to close this and keep it there.

**Closed by benrugg** 2022-11-30 23:34 UTC
