### ISSUE TITLE
Animated new image from last AI image

### ISSUE THREAD

**Issue by Jayohsh** [benrugg/AI-Render#81] opened 2023-03-24 12:19 UTC
### Describe the feature you'd like to see:

Hey Ben,

Firstly, this is an ace plug in. I've started testing with it straight away and I'm really enjoying it's freedom.

A feature i would love is starting an animation as per usual but then moving that animation into using the 'New Image from last ai image' function to continue the animation. 

The current work around I have is to Render animate, then import the image through the compositor and manually press 'New image from last ai Image'. 
Not idea for more then a few frames.

And chance something like that can be implemented. 

Thanks

Josh

**Comment by benrugg** [comment] 2023-03-24 14:34
Glad you're enjoying it 😊 I'm going to close this as a duplicate of #17. I do think this would be a very useful feature. I think even more valuable will be integrating with ControlNet, because that's where we should really be able to get more stable animation. That's going to be my next project!

**Closed by benrugg** 2023-03-24 14:34 UTC
