### ISSUE TITLE
AI Renderer not working

### ISSUE THREAD

**Issue by QuinzyDev** [benrugg/AI-Render#8] opened 2022-10-18 20:59 UTC
### Describe the bug

After rendering, nothing changes. In the AI Render Tab, the node "AI Render" is greyed out. 

### To reproduce

Every time I try to render it.

### Screenshots/video

<img width="1912" alt="Render AI Console" src="https://user-images.githubusercontent.com/68570704/196543476-0bd8d6aa-e306-4f61-bb04-d16d74dd83d6.PNG">

### Environment

- AI Render version: 
- Blender version: 
- Operating system: (Windows, OS X, etc)

### Logs

Traceback (most recent call last):
  File "C:\Users\henri\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\AI-Render\task_queue.py", line 12, in execute_queued_functions
    function()
  File "C:\Users\henri\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\AI-Render\operators.py", line 308, in send_to_api
    img = bpy.data.images.load(tmp_filename, check_existing=True)
RuntimeError: Error: Cannot read '/tmp\ai-render-temp/ai-render-1666126304-2-after.png': No such file or directory

**Comment by benrugg** [comment] 2022-10-18 21:28
Looks like a duplicate of #4. You should be able to fix it by clearing out the "temporary files" preference in Blender: https://github.com/benrugg/AI-Render/issues/4#issuecomment-1281347158

I will also be fixing this in a release very soon!

**Comment by benrugg** [comment] 2022-10-18 21:28
@QuinzyDev by the way, thank you for posting the log!

**Closed by benrugg** 2022-10-18 21:28 UTC
