### ISSUE TITLE
Still seeing server timeouts?

### ISSUE THREAD

**Issue by markwendell** [benrugg/AI-Render#52] opened 2022-12-02 18:14 UTC
### Describe the bug

Looks like you've been working on fixes for server timeouts, but it appears I'm still seeing some.

The install works fine, default settings. My API-Key account connects to the server just fine through the dreamstudio brower UI, so I know the server is responsive.... just not in the Blender session. Note that this was working for me just fine about two weeks ago.

Help appreciated!

Log screenshot included.

### To reproduce

Install in default-cube scene, connect api key and set resolution, type a simple prompt, hit render.

Render appears, but the ai_render node fails after about 15 seconds.

### Error log

see attached image 
(Is there a way to cut-and-paste the log from blender?)

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux): 

 v0-6-6 plugin
Blender 3.1.2 and 3.3.1 both tried
Windows 10 pro

### Screenshots/video

![blender_render_ai_0-6-6_errorlog](https://user-images.githubusercontent.com/4684128/205358173-c9c8ec61-552e-4dfa-83db-48be5aaff6e0.JPG)

**Comment by benrugg** [comment] 2022-12-02 18:32
I am pretty sure the error you're seeing is actually from the old version of AI Render. It looks like you updated it, but maybe you still need to restart Blender? Can you try that and let me know if it fixes it?

**Comment by ocmino** [comment] 2022-12-03 15:14
I have the exact same issue. Tried to remove and reinstall it but the same error keep occurring,

**Comment by benrugg** [comment] 2022-12-03 15:59
Hmm, very strange... Are you guys both still seeing this even after restarting Blender? @ocmino @markwendell

**Comment by benrugg** [comment] 2022-12-03 16:03
If you are still seeing this, could you send me two more pieces of info:
1. The full error log (on Windows: In Blender: Window > Toggle System Console; on Mac: you have to run Blender from a terminal with `/Applications/Blender.app/Contents/MacOS/Blender` and then you'll see the error in the terminal)
2. The prompt text you're using

**Comment by benrugg** [comment] 2022-12-04 21:15
@ocmino @markwendell are you guys still seeing this error?

**Comment by TeiYTChen** [comment] 2022-12-05 03:01
I have the same problem, too!
The error dosen't came up sometime but the render images still can't show up.

**Comment by benrugg** [comment] 2022-12-05 04:03
@TeiYTChen have you restarted Blender after updating AI Render?

**Comment by TeiYTChen** [comment] 2022-12-05 05:25
No matter how I change the style, it always render the same weird image><
Here's the full error log:
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.stability.ai', port=443): Max retries exceeded with url: /v1alpha/generation/stable-diffusion-v1-5/image-to-image (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000253F55E
<img width="1906" alt="ai-render_bug" src="https://user-images.githubusercontent.com/119657367/205555835-22b0d842-1b6d-4c7a-8a02-298df9afdbc9.png">
90C0>, 'Connection to api.stability.ai timed out. (connect timeout=60)'))

**Comment by benrugg** [comment] 2022-12-05 06:03
Ok, thanks for posting the error log. That is definitely just timing out from DreamStudio's servers either being too overloaded or having a temporary issue. That's helpful for me to see, so I can handle that error better. 

In the meantime, I would suggest trying a smaller image size, or just trying again later (which sucks, I know!). 

Typically, the server responds in 3-6 seconds.

**Comment by TeiYTChen** [comment] 2022-12-05 06:11
Thank you so much for the quick reply!!
I'll try rendering the image in a smaller size later~

**Comment by benrugg** [comment] 2022-12-07 02:58
This should be fixed in fdd869b19933b662b17140f5e719bcac1ab66ba4 (and released in the latest release). 

Please let me know if you see this error in the future!

**Closed by benrugg** 2022-12-07 02:58 UTC
Labels: question
