### ISSUE TITLE
controlnet is installed but blender can't acess them

### ISSUE THREAD

**Issue by evilkoolade** [benrugg/AI-Render#129] opened 2023-10-08 19:49 UTC
### Describe the bug

i can use controlnet in automatic but blender still cant access controlnet it just gives me "couldn't get a list of available controlnet models from automatic1111"

### To reproduce

i seem to be the only one with this issue and I can't tell you how to reproduce it because its all i have 

### Error log

couldn't get a list of available controlnet models from automatic11

### Environment

- Blender version (upper right corner of splash screen): 3.6
- AI Render version (find in Preferences > Add-ons): 0.9.1
- Operating system (Windows/Mac/Linux): windows 10

**Comment by benrugg** [comment] 2023-10-08 19:57
Possibly a duplicate of #128. I got these two issues and a third person messaging via blendermarket within 24 hours, so I'm guessing that maybe something in Automatic1111 has changed. I will take a lot at it asap.

**Comment by benrugg** [comment] 2023-10-08 22:02
Ok, I've been looking into this and #128 for a while. I think it's likely that your error is either because Automatic1111 isn't updated, or because ControlNet isn't activated. I know you said you can use it in Automatic1111, but the error you pasted suggests that possibly it's not running, or it's crashing. 

Here is what I'd suggest:

1. Make sure Automatic1111 is updated. (It used to auto-update when run, but it doesn't do that anymore!). In a terminal window, change directory to Automatic1111 `cd wherever` and then run `git stash; git pull; git stash pop`
2. Make sure ControlNet is updated and is running. (See the screenshot). Try "Check for Updates" then "Apply and Restart UI". And obviously make sure the checkbox is checked.

<img width="963" alt="Screenshot 2023-10-08 at 4 58 31 PM" src="https://github.com/benrugg/AI-Render/assets/1221274/4778d1fb-d94f-4e75-bfd4-cb24cc3d21a5">

If it still doesn't work for you, paste the error log from Automatic1111's terminal window and hopefully that will help me diagnose it.

**Closed by benrugg** 2023-10-08 22:02 UTC
